// <auto-generated />
namespace Askaca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class addarte7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addarte7));
        
        string IMigrationMetadata.Id
        {
            get { return "201403051729205_addarte7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
